'use strict';
const OPTIONS=[
 {name:'Motor em movimento',label:'Visão do conjunto',desc:'Um painel escuro acompanha o ponto em que cada pedido está e o que o faz avançar.',use:'Para uma explicação visual do começo ao fim',preview:'O motor avança.<br>O pedido fica guardado.',titles:['Um roteiro, vários pedidos','O motor avança até precisar esperar','Escolher um caminho ou abrir dois','O prazo vence. A mensagem chega.','O trabalho termina ou pede atenção']},
 {name:'Roteiro e execuções',label:'Do desenho à execução',desc:'Uma composição clara separa as regras do roteiro da vida de cada pedido.',use:'Para quem está vendo um motor pela primeira vez',preview:'O roteiro é um.<br>Os pedidos são vários.',titles:['O roteiro e os pedidos que seguem por ele','Cada tipo de tarefa tem uma forma de continuar','As regras controlam os caminhos','Cada espera tem um motivo','A integração tem um trabalho a cumprir']},
 {name:'Diário de um pedido',label:'Foco no que fica guardado',desc:'Acompanhe o registro de cada acontecimento, das primeiras informações à conclusão.',use:'Para explicar estado, dados e retomada',preview:'Onde parou.<br>O que já aconteceu.',titles:['Cada pedido tem seu próprio registro','Uma resposta muda os dados e o andamento','O registro mostra quais caminhos estão ativos','O motor guarda o que está esperando','Uma falha também entra no histórico']},
 {name:'Caminhos do motor',label:'Foco nas regras do percurso',desc:'O mapa ganha destaque para explorar escolhas, trabalhos simultâneos e pontos de encontro.',use:'Para aprofundar decisões, prazos e mensagens',preview:'Escolher. Dividir.<br>Esperar os dois.',titles:['O início coloca um pedido no caminho','Uma tarefa concluída libera a continuação','Um caminho escolhido, dois trabalhos abertos','Tempo e mensagens liberam esperas diferentes','O fim depende dos trabalhos pendentes']},
 {name:'Mesa de experimentos',label:'Aprender experimentando',desc:'Troque o pedido, antecipe o relógio, envie a mensagem errada e provoque uma falha.',use:'Para apresentar com participação do público',preview:'E se a mensagem<br>for de outro pedido?',titles:['Dois pedidos mudam juntos?','O motor avança sem a pessoa responder?','Um trabalho pronto já libera o caminho?','Qual mensagem libera qual pedido?','E se o serviço falhar três vezes?']}
];
const CHAPTERS=['Começar','Executar','Decidir','Esperar','Concluir'];
const TEXTS=[
 {lead:'O roteiro define as etapas e as regras. Cada início cria um pedido independente seguindo esse roteiro.',detail:'O motor dá um número ao pedido, guarda suas informações e começa a percorrer as etapas. Outros pedidos podem usar o mesmo roteiro.',lesson:'Crie dois pedidos. Depois, avance um deles e observe que o outro continua onde estava.'},
 {lead:'O motor executa o que estiver pronto. Ao chegar a uma tarefa de uma pessoa, guarda o ponto atual e espera.',detail:'Quando a resposta chega, ele registra os dados e continua. Um trabalho automático pode consultar outro sistema e devolver o resultado.',lesson:'Concluir uma tarefa libera a continuação prevista no roteiro. Cada clique aqui representa um acontecimento recebido pelo motor.'},
 {lead:'Uma escolha segue a regra dos dados. Uma divisão abre trabalhos que podem avançar de forma independente.',detail:'Neste roteiro, a prioridade escolhe um caminho. Mais adiante, o motor abre dois trabalhos. O encontro só libera a continuação quando ambos terminam.',lesson:'Conclua apenas um trabalho e observe a espera pelo outro. Você pode terminar em qualquer ordem.'},
 {lead:'O motor guarda a razão da espera: um prazo que precisa vencer ou uma mensagem que precisa chegar.',detail:'Mensagens podem vir por um canal compartilhado. Uma integração lê esse canal e localiza o pedido pelo assunto esperado e pelo número.',lesson:'Uma mensagem de outro pedido não libera este. A passagem do tempo também não substitui uma mensagem esperada.'},
 {lead:'O motor deixa um trabalho disponível. Um executor o reserva, chama o serviço e devolve sucesso ou falha.',detail:'Se falhar, a política deste exemplo permite tentar novamente. Ao esgotar as tentativas, o pedido fica pendente de intervenção.',lesson:'O pedido só termina depois do sucesso e de chegar ao fim do roteiro, sem outros caminhos ativos.'}
];
const ALT={
 2:['O roteiro publicado é a referência comum. Os pedidos têm números, informações e posições próprias.','O início coloca o pedido em movimento. A tarefa humana espera uma resposta. A tarefa automática executa um trabalho ou aguarda seu executor.','O desenho define se o motor escolhe uma saída ou abre várias. O encontro deste exemplo espera os dois trabalhos abertos.','Um prazo pode liberar a continuação. Uma mensagem precisa encontrar uma espera compatível no pedido certo.','A responsabilidade de chamar o serviço fica com o executor. O motor acompanha o trabalho e seu resultado.'],
 3:['No registro aparecem o número, a versão do roteiro e a etapa atual de cada pedido.','“Prioridade: sim” ou “Prioridade: não” passa a fazer parte do pedido quando a tarefa recebe a resposta.','Dois trabalhos abertos significam duas posições ativas no mesmo pedido. Um pode terminar antes do outro.','A data prevista e o assunto aguardado permitem saber por que um pedido ainda não continuou.','Fechar e reabrir a página recupera o progresso aceito desta demonstração. O motor real guarda esse andamento fora da memória da tela.'],
 4:['O início cria uma execução. O percurso avança pelas conexões definidas no roteiro.','Aqui o motor cria uma tarefa humana. Quando ela termina, uma consulta automática precede a escolha do caminho.','A primeira decisão escolhe uma saída. A divisão seguinte abre duas. O encontro reúne essas duas chegadas.','Neste exemplo, primeiro vence o prazo. Depois o pedido aguarda a confirmação do agendamento.','O trabalho final integra outro serviço. Sucesso permite chegar ao fim. Falha mantém uma pendência tratável.'],
 5:['Inicie Ana e Bruno. Os dois usam o mesmo roteiro. Selecione um e experimente avançar apenas esse pedido.','Deixe a tarefa aberta. Nada avança por esperar mais tempo. Depois simule a resposta e compare o registro.','Finalize o preparo antes do registro. O motor ainda precisa da segunda chegada ao ponto de encontro.','Avance o relógio, envie um assunto diferente ou use outro número. Depois entregue a confirmação certa.','Reserve o trabalho e provoque uma falha. Avance o relógio e repita até esgotar as tentativas. Corrija a causa e libere outra tentativa.']
};
const STAGES={human:'Aguardando uma pessoa',parallel:'Dois trabalhos em andamento',timer:'Aguardando o prazo',message:'Aguardando confirmação',integration:'Integração pendente',incident:'Precisa de intervenção',ended:'Concluído'};
const $=s=>document.querySelector(s);
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let mode=Number(new URLSearchParams(location.search).get('opcao'));
if(!Number.isInteger(mode)||mode<1||mode>5)mode=0;
let engine=MotorDemo.create(),slide=0,storageAvailable=true,toastTimer;
const instance=()=>MotorDemo.current(engine);
const clock=m=>`${String(9+Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
const B=(action,label,kind='',disabled=false)=>`<button type="button" data-action="${action}" class="${kind}" ${disabled?'disabled':''}>${label}</button>`;
function save(){try{localStorage.setItem('inside-motor-v2-'+mode,JSON.stringify({engine,slide}));}catch{storageAvailable=false;}}
function restore(){try{const v=JSON.parse(localStorage.getItem('inside-motor-v2-'+mode)||'null');if(v?.engine?.schema===2&&Array.isArray(v.engine.instances)&&Number.isInteger(v.slide)&&v.slide>=0&&v.slide<5){engine=v.engine;slide=v.slide;}}catch{storageAvailable=false;}}
function announce(t){$('#announcement').textContent=t;}
function toast(t){document.querySelector('.toast')?.remove();clearTimeout(toastTimer);const el=document.createElement('div');el.className='toast';el.textContent=t;$('.deck')?.append(el);announce(t);toastTimer=setTimeout(()=>el.remove(),4500);}
function send(event){const result=MotorDemo.dispatch(engine,event);save();render();if(result)toast(result);}
function rank(i){return !i?-1:({human:1,parallel:2,timer:3,message:3,integration:4,incident:4,ended:5})[i.stage];}
function prepare(target){
 if(!instance())MotorDemo.dispatch(engine,{type:'start',person:'Ana'});
 let i=instance();
 if(target>=2&&i.stage==='human')MotorDemo.dispatch(engine,{type:'human',priority:true});
 if(target>=3&&i.stage==='parallel')for(const branch of ['record','prepare'])if(!i.branches[branch])MotorDemo.dispatch(engine,{type:'branch',branch});
 if(target>=4&&i.stage==='timer')MotorDemo.dispatch(engine,{type:'tick',minutes:Math.max(0,i.due-engine.clock)});
 if(target>=4&&i.stage==='message')MotorDemo.dispatch(engine,{type:'message',id:i.id,name:'Agendamento confirmado'});
 save();render();toast('Exemplo preparado. Os passos anteriores estão registrados nas notas.');
}
function gallery(){
 document.title='O motor por dentro • Cinco apresentações';
 $('#app').innerHTML=`<main id="main" class="gallery"><header class="gallery-top"><div class="wordmark"><b></b>Dynamic Journey</div><span>O funcionamento do motor / 05 propostas</span></header><section class="gallery-intro"><div><p class="eyebrow">Por dentro do motor</p><h1>Como um pedido<br>ganha andamento.</h1></div><p>Cinco apresentações para entender o que o motor executa, o que ele guarda e por que ele espera. Abra uma e experimente.</p></section><section class="options" aria-label="Escolha uma apresentação">${OPTIONS.map((o,i)=>`<a class="option" href="?opcao=${i+1}"><div class="preview preview-${i+1}" aria-hidden="true"><div class="mini-label">${o.label}</div><strong>${o.preview}</strong>${i===0?'<div class="mini-line"><i></i><i class="active"></i><i></i><i></i></div>':i===1?'<div class="mini-pair"><span>Pedido 101<br>Aguardando a pessoa</span><span>Pedido 102<br>Aguardando o serviço</span></div>':i===2?'<div class="mini-record">09:00 &nbsp; Iniciado<br>09:00 &nbsp; Tarefa aberta<br>09:10 &nbsp; Prazo cumprido</div>':i===3?'<div class="mini-branch"><span>Registrar pedido</span><span>Preparar atendimento</span></div>':'<div class="mini-chat">Mensagem recebida.<br>Qual pedido estava esperando?</div>'}</div><div class="option-heading"><span>0${i+1}</span><h2>${o.name}</h2></div><p>${o.desc}</p><span class="open">${o.use} ↗</span></a>`).join('')}</section><footer class="gallery-foot"><span>5 slides por opção. Início, tarefas, caminhos, esperas e integrações.</span><span>Exemplos fictícios. Funciona sem internet.</span></footer></main>`;
}
function memory(){
 const i=instance();
 const rows=i?[['Situação',STAGES[i.stage]]]:[];
 if(i&&slide<=1)rows.push(['Roteiro','Instalação / versão '+i.version]);
 if(i&&(slide===1||slide===2))rows.push(['Prioridade',i.priority===null?'Ainda não informada':i.priority?'Sim':'Não']);
 if(i&&slide===2)rows.push(['Caminho escolhido',i.route||'Ainda não escolhido'],['Registro',i.branches.record?'Concluído':'Pendente'],['Preparo',i.branches.prepare?'Concluído':'Pendente']);
 if(i?.stage==='timer')rows.push(['Prazo previsto',clock(i.due)]);
 if(i?.stage==='message')rows.push(['Mensagem esperada','Agendamento confirmado']);
 if(i&&rank(i)>=4&&i.stage!=='ended')rows.push(['Tentativas restantes',i.retries],['Quem reservou',i.lockedBy||'Ninguém']);
 const history=i?.history.slice(mode===3?-4:-3)||[];
 return `<aside class="memory"><h2>${mode===3?'Registro do pedido':'O que o motor guarda'}</h2><div class="record"><div class="record-id">${i?'#'+i.id:'Nenhum pedido'}</div><p>${i?E(i.person):'O início cria um registro próprio.'}</p></div><dl>${rows.map(([k,v])=>`<div class="data-row ${k==='Situação'||k==='Prioridade'?'changed':''}"><dt>${k}</dt><dd>${E(v)}</dd></div>`).join('')}</dl>${history.length?`<ol class="event-log" aria-label="Últimos acontecimentos">${history.map(h=>`<li><time>${clock(h.at)}</time><span>${E(h.text)}</span></li>`).join('')}</ol>`:''}</aside>`;
}
function node(label,kind='',hint=''){return `<div class="process-node ${kind}"><span class="node-mark" aria-hidden="true">${kind.includes('event')?'○':kind.includes('choice')?'◇':kind.includes('join')?'+':'□'}</span><span>${label}${hint?`<small>${hint}</small>`:''}</span></div>`;}
function prereq(){return `<div class="surface"><div class="status">Exemplo ainda não preparado</div><h2>Este trecho vem depois</h2><p>Você pode percorrer os slides anteriores ou preparar um pedido neste ponto do roteiro.</p>${B('prepare','Preparar este exemplo','primary')}<p class="callout">A preparação simula os passos anteriores e deixa o histórico nas notas.</p></div>`;}
function startPanel(){
 return `<div class="surface engine-surface"><div class="bench-title"><span>Roteiro publicado</span><span>Instalação / versão 1</span></div><div class="process-line">${node('Início','event')}${node('Gerar número','', 'Trabalho automático')}${node('Confirmar dados',instance()?.stage==='human'?'active':'','Trabalho de uma pessoa')}</div><p class="diagram-caption">O início coloca o pedido no roteiro. O motor executa a primeira atividade e para na tarefa humana.</p><div class="action-row">${B('start',engine.instances.length?'Criar outro pedido':'Iniciar o pedido de Ana','primary',engine.instances.length>=4)}</div><div class="instance-list">${engine.instances.map(i=>`<button data-instance="${i.id}" aria-pressed="${engine.active===i.id}"><span>#${i.id} &nbsp; ${E(i.person)}</span><small>${STAGES[i.stage]}</small></button>`).join('')}</div></div>`;
}
function taskPanel(){
 const i=instance();if(!i)return prereq();
 return `<div class="surface engine-surface"><div class="status">${i.stage==='human'?'Tarefa aberta para uma pessoa':'Tarefa humana já concluída'}</div><div class="process-stack">${node('Confirmar os dados',i.stage==='human'?'active':'done','Aguarda uma resposta')}${node('Consultar o cadastro',i.stage==='human'?'':'done','O serviço devolve o resultado')}${node('Aplicar as regras',rank(i)>=2?'done':'','O motor segue com os dados do pedido')}</div><div class="response-example"><span class="eyebrow">Simular a resposta recebida</span><label for="priority">Este pedido tem prioridade?</label><select id="priority" ${i.stage!=='human'?'disabled':''}><option value="yes" ${i.priority!==false?'selected':''}>Sim</option><option value="no" ${i.priority===false?'selected':''}>Não</option></select>${B('human','Receber conclusão da tarefa','primary',i.stage!=='human')}</div><p class="diagram-caption">${i.stage==='human'?'Até chegar a resposta, o motor preserva a tarefa aberta.':'O motor guardou a prioridade, executou a consulta e abriu os próximos trabalhos.'}</p></div>`;
}
function gatewayPanel(){
 const i=instance();if(rank(i)<2)return prereq();
 return `<div class="surface engine-surface"><div class="gate-label"><span class="gate-symbol">◇</span><div><h2>Uma escolha</h2><p>Prioridade: ${i.priority?'sim':'não'}. Apenas uma saída.</p></div></div><div class="route-options"><div class="${i.priority?'selected':''}">Atendimento prioritário${i.priority?'<small>Escolhido</small>':''}</div><div class="${!i.priority?'selected':''}">Atendimento comum${!i.priority?'<small>Escolhido</small>':''}</div></div><div class="gate-label parallel-label"><span class="gate-symbol">+</span><div><h2>Dois trabalhos abertos</h2><p>Ambos pertencem ao pedido #${i.id}.</p></div></div><div class="parallel-work"><div>${node('Registrar pedido',i.branches.record?'done':'active',i.branches.record?'Concluído':'Pendente')}${B('branch-record','Concluir registro','',i.stage!=='parallel'||i.branches.record)}</div><div>${node('Preparar atendimento',i.branches.prepare?'done':'active',i.branches.prepare?'Concluído':'Pendente')}${B('branch-prepare','Concluir preparo','',i.stage!=='parallel'||i.branches.prepare)}</div></div><div class="join-line"><span>+</span><p>${i.branches.record&&i.branches.prepare?'Os dois chegaram. O motor liberou a continuação.':'O encontro espera a chegada dos dois trabalhos.'}</p></div></div>`;
}
function waitPanel(){
 const i=instance();if(rank(i)<3)return prereq();
 const waiting=i.stage==='timer';
 return `<div class="surface engine-surface"><div class="timer-row"><div><span class="eyebrow">Relógio do exemplo</span><div class="clock-value">${clock(engine.clock)}</div></div><div><span class="status">${waiting?'Prazo pendente':'Prazo cumprido'}</span><p>Esperar até ${clock(i.due)}</p></div></div><div class="action-row">${B('tick5','Avançar 5 minutos','primary')}</div><div class="message-path"><span>Canal de mensagens</span><b>confirmações de agendamento</b><small>A integração lê o canal e procura a espera compatível.</small></div><label for="message-kind">Assunto da mensagem</label><select id="message-kind"><option>Agendamento confirmado</option><option>Pagamento confirmado</option></select><label for="message-id">Número do pedido na mensagem</label><select id="message-id"><option value="${i.id}">Este pedido (#${i.id})</option><option value="999">Outro pedido (#999)</option>${engine.instances.filter(p=>p.id!==i.id).map(p=>`<option value="${p.id}">${E(p.person)} (#${p.id})</option>`).join('')}</select>${B('message','Entregar mensagem','primary')}<p class="diagram-caption">${waiting?'A espera por mensagem ainda não abriu. Ela começa depois do prazo e do envio do convite.':i.stage==='message'?'Este pedido espera “Agendamento confirmado” com o número #'+i.id+'.':'Este pedido já recebeu a confirmação. Repeti-la não conclui o trabalho seguinte.'}</p>${engine.deliveries.length?`<div class="delivery ${engine.deliveries.at(-1).accepted?'accepted':''}">${engine.deliveries.at(-1).accepted?'Última mensagem encontrou uma espera.':'Última mensagem não encontrou uma espera compatível.'}</div>`:''}</div>`;
}
function integrationPanel(){
 const i=instance();if(rank(i)<4)return prereq();
 if(i.stage==='ended')return `<div class="surface engine-surface"><div class="status">Pedido concluído</div><div class="end-mark">✓</div><h2>O motor chegou ao fim</h2><p>O serviço devolveu sucesso. O trabalho terminou e não há outros caminhos ativos neste pedido.</p><div class="receipt">${i.person} / #${i.id}<br>${i.attempts} ${i.attempts===1?'tentativa realizada':'tentativas realizadas'}</div><div class="action-row">${B('old-response','Repetir resposta antiga')}${B('resume','Recarregar o registro')}</div><p class="diagram-caption">O pedido concluído continua disponível para consulta nesta demonstração.</p></div>`;
 return `<div class="surface engine-surface"><div class="status">${i.stage==='incident'?'Intervenção necessária':i.lockedBy?'Trabalho reservado':'Trabalho disponível para execução'}</div><h2>Efetivar a instalação</h2><div class="integration-flow"><span>Motor</span><span>Executor</span><span>Serviço externo</span></div><p>O motor guarda o trabalho. O executor faz a chamada e informa o resultado.</p><div class="attempts"><strong>${i.retries}</strong><span>${i.retries===1?'tentativa restante':'tentativas restantes'}<small>Política escolhida para este exemplo</small></span></div>${i.stage==='incident'?`${B('repair','Corrigir causa e liberar tentativa','primary')}`:`<div class="action-row">${B('claim-a','Executor A assume','primary',engine.clock<i.retryAt)}${B('claim-b','Executor B tenta assumir','',engine.clock<i.retryAt)}</div><p class="lock-caption">${i.lockedBy?i.lockedBy+' reservou até '+clock(i.lockUntil)+'.':engine.clock<i.retryAt?'Nova tentativa a partir de '+clock(i.retryAt)+'.':'Sem reserva ativa.'}</p><div class="action-row">${B('succeed','Serviço responde com sucesso','',!i.lockedBy)}${B('fail','Serviço falha','',!i.lockedBy)}</div>`}<div class="action-row">${B('tick2','Avançar 2 minutos')}${B('resume','Recarregar o registro')}</div><p class="diagram-caption">Uma reserva tem prazo. Uma chamada externa pode precisar de proteção própria contra repetição.</p></div>`;
}
function renderDeck(){
 const o=OPTIONS[mode-1],t=TEXTS[slide],i=instance();document.title=`${o.name} • ${slide+1}/5`;
 $('#app').innerHTML=`<div class="deck mode-${mode}"><header class="deck-top"><div class="deck-brand"><a href="index.html">↖ As cinco opções</a><strong>0${mode} / ${o.name}</strong></div><div class="top-actions">${B('notes','Notas')}${B('reset','Recomeçar')}${B('fullscreen','Tela cheia')}</div></header><main id="main" class="slide-wrap"><div class="slide-heading"><span class="chapter">0${slide+1}</span><h1 tabindex="-1">${o.titles[slide]}</h1></div><div class="instance-switch"><span>Pedido em foco</span>${engine.instances.map(p=>`<button data-instance="${p.id}" aria-pressed="${p.id===engine.active}">${E(p.person)} #${p.id}</button>`).join('')||'<span>Inicie um pedido para acompanhar.</span>'}<span class="global-clock">Relógio ${clock(engine.clock)}</span></div><div class="composition reveal"><section class="narrative"><p class="eyebrow">${o.label}</p><p class="lead">${t.lead}</p><p class="detail">${ALT[mode]?.[slide]||t.detail}</p><p class="lesson">${t.lesson}</p>${mode===5?`<div class="experiment"><span>Experimento ${slide+1}</span><p>${['Crie dois pedidos e escolha apenas um para avançar.','Mude a prioridade e receba a conclusão da tarefa.','Termine o preparo antes de concluir o registro.','Envie a mensagem errada antes da confirmação certa.','Faça o serviço falhar até pedir intervenção.'][slide]}</p></div>`:''}</section><div class="workbench">${[startPanel,taskPanel,gatewayPanel,waitPanel,integrationPanel][slide]()}</div>${memory()}</div><ol class="trail" aria-label="Capítulos da apresentação">${CHAPTERS.map((c,n)=>`<li class="${n===slide?'current':n<slide?'done':''}" ${n===slide?'aria-current="step"':''}>${String(n+1).padStart(2,'0')} &nbsp;${c}</li>`).join('')}</ol></main><footer class="deck-bottom"><nav class="slide-dots" aria-label="Slides">${CHAPTERS.map((c,n)=>`<button data-slide="${n}" aria-label="Slide ${n+1}: ${c}" aria-current="${n===slide}">0${n+1}</button>`).join('')}</nav><span class="footer-hint">Setas do teclado navegam. Os controles simulam acontecimentos.</span><div class="paging">${B('prev','Anterior','',slide===0)}<span>${slide+1} / 5</span>${slide===4?'<a href="index.html">Ver opções</a>':B('next','Próximo','primary')}</div></footer><div class="example-label"><span>Simulação didática. Roteiro, dados e relógio fictícios.</span><span>${storageAvailable?'Progresso guardado neste navegador.':'Progresso disponível apenas enquanto esta página está aberta.'}</span></div></div>`;
}
function render(){mode?renderDeck():gallery();}
function go(n){if(n<0||n>4)return;slide=n;save();render();$('.slide-heading h1')?.focus({preventScroll:true});announce('Slide '+(n+1));window.scrollTo({top:0,behavior:'instant'});}
const SOURCES=[
 ['Conceitos, roteiro e execuções','https://docs.camunda.org/manual/7.24/user-guide/process-engine/process-engine-concepts/'],
 ['Avanço, espera e persistência','https://docs.camunda.org/manual/7.24/user-guide/process-engine/transactions-in-processes/'],
 ['Dados do pedido','https://docs.camunda.org/manual/7.24/user-guide/process-engine/variables/'],
 ['Escolha de um caminho','https://docs.camunda.org/manual/7.24/reference/bpmn20/gateways/exclusive-gateway/'],
 ['Divisão e encontro de caminhos','https://docs.camunda.org/manual/7.24/reference/bpmn20/gateways/parallel-gateway/'],
 ['Espera por prazo','https://docs.camunda.org/manual/7.24/reference/bpmn20/events/timer-events/'],
 ['Mensagens e identificação da espera','https://docs.camunda.org/manual/7.24/reference/bpmn20/events/message-events/'],
 ['Trabalhos externos, reservas e tentativas','https://docs.camunda.org/manual/7.24/user-guide/process-engine/external-tasks/']
];
function showNotes(){
 const technical=[
  'O roteiro representa uma definição de processo publicada. Cada pedido representa uma instância, vinculada à versão 1 neste exemplo. O evento de início cria a execução. Uma tarefa automática gera o protocolo antes da primeira user task. Um início também pode ser disparado por mensagem ou agendamento, conforme o modelo.',
  'A tarefa humana é uma user task. Ao concluir, as respostas aceitas tornam-se variáveis com escopo de processo neste exemplo. A consulta ao cadastro representa uma service task síncrona de sucesso. A execução percorre as atividades até as próximas esperas. Atividades podem ser configuradas com fronteiras assíncronas. Em caso de falha síncrona, a operação pode retornar ao último ponto persistido.',
  'O primeiro gateway é exclusivo: a condição da prioridade escolhe uma saída. Em Camunda 7, condições concorrentes podem depender da ordem no modelo. Uma saída padrão pode tratar o caso sem correspondência. O segundo gateway é paralelo: abre duas execuções no mesmo processo. O join estruturado espera as duas entradas. Independência lógica não exige que as atividades usem threads simultâneas. Outros tipos incluem gateways inclusivos e baseados em eventos.',
  'O timer deste exemplo é intermediário e espera uma duração de 10 minutos. Em um motor real, o executor de jobs dispara depois do vencimento conforme disponibilidade, não necessariamente no milissegundo exato. Depois, um serviço envia o convite e abre a espera por mensagem. O tópico é um canal no sistema de mensagens. Um consumidor ou conector lê o tópico e correlaciona a mensagem com nome e identificador da instância. Um tópico de mensagens não é o mesmo que o tópico de external tasks. Neste modelo local, mensagens sem espera compatível são registradas e não ficam em buffer para uso futuro. Política real de reentrega depende da integração.',
  'O trabalho final usa o modelo de external task do Camunda 7: um worker busca e reserva o trabalho por um prazo, realiza a integração e reporta conclusão ou falha. O exemplo define 3 tentativas, espera de 2 minutos e reserva de 2 minutos. Esses valores são escolhas didáticas, não padrões universais. A política de retry é informada pelo executor na falha. Ao zerar tentativas, há um incidente. Após corrigir a causa, uma intervenção pode liberar tentativas. A reserva não garante efeito externo exatamente uma vez. Serviços precisam tratar possíveis duplicidades. O evento de fim conclui esta instância quando não restam execuções ativas.'
 ];
 const i=instance();
 $('#notes-body').innerHTML=`<p>${technical[slide]}</p><h3>Como demonstrar</h3><p>Crie Ana e Bruno e avance apenas um pedido. Compare a prioridade, conclua os trabalhos em ordens diferentes e avance o relógio. Teste mensagem com assunto ou número errado. Na integração final, tente reservar com dois executores, provoque falhas e recupere o trabalho.</p><h3>Registro do pedido ${i?'#'+i.id:''}</h3>${i?`<ol>${i.history.map(h=>`<li>${clock(h.at)}: ${E(h.text)}</li>`).join('')}</ol>`:'<p>Nenhum pedido iniciado.</p>'}<h3>Fontes e alcance</h3><p>Modelo didático baseado no comportamento documentado do Camunda 7.24. O roteiro fictício foi criado para a apresentação. A integração de tópicos também foi conferida no KafkaConnectorWorker deste projeto. Os controles substituem os acontecimentos externos e o relógio. Não há conexão com serviços reais.</p><ul>${SOURCES.map(([t,u])=>`<li><a href="${u}" target="_blank" rel="noopener">${t}</a></li>`).join('')}</ul><p>O armazenamento local reproduz a ideia de guardar andamento. Um motor real usa persistência própria, com controle de concorrência e transações. O registro de histórico depende da configuração de retenção. O comportamento demonstrado não pretende ser idêntico em todos os motores de mercado.</p>`;
 $('#notes').showModal();
}
document.addEventListener('click',async e=>{
 const b=e.target.closest('button');if(!b||b.disabled)return;
 if(b.dataset.slide!==undefined){go(Number(b.dataset.slide));return;}
 if(b.dataset.instance){send({type:'select',id:Number(b.dataset.instance)});return;}
 const a=b.dataset.action;
 if(a==='close-notes'){$('#notes').close();return;}
 if(!mode)return;
 switch(a){
  case 'start':send({type:'start',person:['Ana','Bruno','Carla','Diego'][engine.instances.length]||'Ana'});break;
  case 'prepare':prepare(slide);break;
  case 'human':send({type:'human',priority:$('#priority').value==='yes'});break;
  case 'branch-record':send({type:'branch',branch:'record'});break;
  case 'branch-prepare':send({type:'branch',branch:'prepare'});break;
  case 'tick5':send({type:'tick',minutes:5});break;
  case 'tick2':send({type:'tick',minutes:2});break;
  case 'message':send({type:'message',id:Number($('#message-id').value),name:$('#message-kind').value});break;
  case 'claim-a':send({type:'claim',worker:'Executor A'});break;
  case 'claim-b':send({type:'claim',worker:'Executor B'});break;
  case 'fail':send({type:'fail'});break;
  case 'succeed':send({type:'succeed'});break;
  case 'repair':send({type:'repair'});break;
  case 'old-response':send({type:'human',priority:false});break;
  case 'resume':if(storageAvailable){save();location.reload();}else toast('O navegador não permite guardar o exemplo. O registro atual permanece nesta página.');break;
  case 'prev':go(slide-1);break;
  case 'next':go(slide+1);break;
  case 'notes':showNotes();break;
  case 'reset':engine=MotorDemo.create();slide=0;save();render();break;
  case 'fullscreen':try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('Use F11 no navegador para apresentar em tela cheia.');}break;
 }
});
document.addEventListener('keydown',e=>{if(!mode||$('#notes').open||e.ctrlKey||e.metaKey||e.altKey||e.target.closest('input,select,textarea,button,a'))return;if(e.key==='ArrowRight'){e.preventDefault();go(slide+1);}if(e.key==='ArrowLeft'){e.preventDefault();go(slide-1);}});
if(mode)restore();render();
