package com.jouney.transformpublication.bpmn;

import com.jouney.transformpublication.interfaces.publication.PublicationSnapshotRequest;
import com.jouney.transformpublication.interfaces.publication.PublicationSnapshotRequest.FlowNodeRequest;
import java.io.ByteArrayOutputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.camunda.bpm.model.bpmn.Bpmn;
import org.camunda.bpm.model.bpmn.BpmnModelInstance;
import org.camunda.bpm.model.bpmn.builder.AbstractFlowNodeBuilder;
import org.camunda.bpm.model.bpmn.builder.ProcessBuilder;
import org.springframework.stereotype.Component;

/**
 * Transforms the Admin Portal's journey publication snapshot into an executable BPMN 2.0
 * process for Camunda 7. The admin's flow model only allows a single continuous path
 * between the initial element (START/MESSAGE_START_EVENT) and END (FlowValidator on the
 * admin side enforces exactly one outgoing connection per node), so the flow is always a
 * linear chain — this transformer walks it as such rather than a general graph.
 *
 * ponytail: sequence flow ids are auto-generated by the builder, not matched back to the
 * admin's own connection ids — fine for a simulated transform, add a rename pass if the
 * two systems ever need to correlate sequence flows by id.
 */
@Component
public class BpmnTransformer {

    public record Result(String processId, byte[] bpmnXml) {
    }

    public Result transform(PublicationSnapshotRequest request) {
        List<FlowNodeRequest> ordered = orderNodes(request);
        String processId = ProcessIds.forJourney(request.journeyId());

        FlowNodeRequest first = ordered.get(0);
        ProcessBuilder processBuilder = Bpmn.createExecutableProcess(processId).name(request.journeyName());
        AbstractFlowNodeBuilder<?, ?> builder = "MESSAGE_START_EVENT".equals(first.type())
                ? processBuilder.startEvent(first.id()).name(first.name()).message(messageName(first))
                : processBuilder.startEvent(first.id()).name(first.name());

        for (int i = 1; i < ordered.size(); i++) {
            FlowNodeRequest node = ordered.get(i);
            builder = switch (node.type()) {
                case "USER_TASK" -> {
                    var userTask = builder.userTask(node.id()).name(node.name());
                    yield node.formId() != null
                            ? userTask.camundaInputParameter("formId", node.formId().toString())
                            : userTask;
                }
                case "SERVICE_TASK" -> builder.serviceTask(node.id()).name(node.name())
                        .camundaType("external")
                        .camundaTopic(topicName(node));
                case "RECEIVE_TASK" -> builder.receiveTask(node.id()).name(node.name()).message(messageName(node));
                case "END" -> builder.endEvent(node.id()).name(node.name());
                default -> throw new BpmnTransformationException("Unsupported node type: " + node.type());
            };
        }

        BpmnModelInstance model = builder.done();
        Bpmn.validateModel(model);
        return new Result(processId, toXmlBytes(model));
    }

    private List<FlowNodeRequest> orderNodes(PublicationSnapshotRequest request) {
        Map<String, FlowNodeRequest> byId = new HashMap<>();
        for (FlowNodeRequest node : request.flowNodes()) {
            byId.put(node.id(), node);
        }
        Map<String, String> nextByFrom = new HashMap<>();
        for (var connection : request.flowConnections()) {
            nextByFrom.put(connection.sourceNodeId(), connection.targetNodeId());
        }

        FlowNodeRequest current = request.flowNodes().stream()
                .filter(n -> "START".equals(n.type()) || "MESSAGE_START_EVENT".equals(n.type()))
                .findFirst()
                .orElseThrow(() -> new BpmnTransformationException("Flow has no START/MESSAGE_START_EVENT node"));

        List<FlowNodeRequest> ordered = new ArrayList<>();
        ordered.add(current);
        int guard = byId.size() + 1;
        while (!"END".equals(current.type())) {
            if (guard-- <= 0) {
                throw new BpmnTransformationException("Flow traversal did not terminate at an END node (cycle?)");
            }
            String nextId = nextByFrom.get(current.id());
            if (nextId == null) {
                throw new BpmnTransformationException("Node " + current.id() + " has no outgoing connection and is not END");
            }
            current = byId.get(nextId);
            if (current == null) {
                throw new BpmnTransformationException("Connection targets unknown node " + nextId);
            }
            ordered.add(current);
        }
        return ordered;
    }

    private String messageName(FlowNodeRequest node) {
        return "Message_" + node.id();
    }

    private String topicName(FlowNodeRequest node) {
        String connector = node.connectorConfig() != null && node.connectorConfig().connectorType() != null
                ? node.connectorConfig().connectorType().toLowerCase()
                : "generic";
        return connector + "-" + node.id();
    }

    private byte[] toXmlBytes(BpmnModelInstance model) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Bpmn.writeModelToStream(out, model);
        return out.toByteArray();
    }
}
